---
trigger: approve
title: Approve Review
description: Submit an approval for a security review request by team
surfaces:
  - issue
steps:
  - type: form
    style: embedded
    actions:
      submit: Review and submit
    body:
      - type: dropdown
        attributes:
          label: Team
          id: team
          description: Team submitting the approval
          options:
          - label: Test Team 1
            value: team1
          - label: Test Team 2
            value: team2
      - type: dropdown
        attributes:
          label: Approval Status
          id: status
          description: Approval status
          options:
          - label: Approved
            value: approved
          - label: Not Approved
            value: not_approved
      - type: textarea
        attributes:
          label: Comments
          id: comments
          description: Comments on the review
          placeholder: Please provide details about the decision (e.g. why it was approved or not approved, what was taken into consideration) and links to any related issues or documents.
  - type: repository_dispatch
    eventType: tag_approved
  - type: fill
    template: |
      **Team:** {{ data.team }}

      **Status:** {{ data.status }}

      ### Comments
      {{ data.comments }}